[tool.ruff]
line-length = 120
target-version = "py313"
exclude = ["build", "dist", ".venv", "__pycache__", "versions"]
preview = true
 
[tool.ruff.lint]
select = ["E", "F", "W", "I", "B"]
ignore = ["E203"]
extend-select = ["I"]
 
[tool.ruff.lint.per-file-ignores]
"igm_jobs/prompts.py" = ["E501"]
 
[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
 
[tool.isort]
profile = "black"
 
 
[tool.black]
line-length = 120